/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about/index.vue')['default']
    Dialog: typeof import('./src/components/dialog/index.vue')['default']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    NA: typeof import('naive-ui')['NA']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NH3: typeof import('naive-ui')['NH3']
    NIcon: typeof import('naive-ui')['NIcon']
    NIconWrapper: typeof import('naive-ui')['NIconWrapper']
    NImage: typeof import('naive-ui')['NImage']
    NLi: typeof import('naive-ui')['NLi']
    NModal: typeof import('naive-ui')['NModal']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NUl: typeof import('naive-ui')['NUl']
    Svg: typeof import('./src/components/svg/index.vue')['default']
    Update: typeof import('./src/components/update/index.vue')['default']
  }
}
